name: Test self-hosted runner in org
on: [ push, workflow_dispatch ]

jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Install org runner
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      
      - uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: jduimovich-code
          insecure_skip_tls_verify: true

      - name: Install self hosted runner into repository
        uses: redhat-actions/self-hosted-runner-installer@main
        with:
          github_pat: ${{ secrets.ORG_SECRET }}
          runner_labels: repo-label, repo-label-2
  
  test-selfhosted:
    runs-on: [ self-hosted, repo-label, repo-label-2 ]
    needs: install-runner

    steps:
      - run: "hostname"