name: Install Runner and Dispatch Workflows
on: [ push, workflow_dispatch ] 
jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Ensure Runner Installed, then signal workflows
    steps:  
      - uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: jduimovich-code
          insecure_skip_tls_verify: true 
      - name: Ensure self hosted runner is running 
        uses: redhat-actions/self-hosted-runner-installer@main
        with:
          github_pat: ${{ secrets.REPO_TOKEN }}
          runner_labels: openshift
  run-post-runner-ready-workflows:
    runs-on: ubuntu-20.04
    needs: install-runner 
    steps:  
      - name: Signal dependent workflows waiting for runner-ready
        uses: jduimovich/repository-dispatch@main
        id: dispatch
        with:
          github-token: ${{ secrets.REPO_TOKEN }}  
          event-to-dispatch: runner-ready  
      - name: Result from the dispatch
        run: echo "Result ${{ steps.dispatch.outputs.result }}"